# Common
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
session.timeout.ms=45000

# Cluster 1 AWS
bootstrap.servers.1=pkc-921jm.us-east-2.aws.confluent.cloud:9092
sasl.username.1=EH2Z7EQABQU5TGPS
sasl.password.1=cfltK5J73TFj2UiG09jvXT94OxARGXzSIVcJuKTpVNbrpLTMRnkh4HG1ntLwK6Ng

# Cluster 2 GCP
bootstrap.servers.2=pkc-619z3.us-east1.gcp.confluent.cloud:9092
sasl.username.2=AWKGSCGXKYTVRETV
sasl.password.2=cfltcQtwO/9oKti48eXTtE6nbFLJcHFqzqLxEbVtUcAiXdUIQQsFpXFw6kdSfKug
